openapi: 3.0.3
info:
  title: LetsBurn Restaurante API
  description: API for managing restaurant operations
  version: 1.0.0
paths:
  /restaurante/atender-cliente:
    post:
      summary: Atender Cliente
      description: Atende um cliente e cria um atendimento.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RequestAtenderClienteDTO'
      responses:
        '200':
          description: Atendimento criado com sucesso.
          content:
            application/json:
              schema:
                type: integer
                format: int64
  /restaurante/fazer-pedido/{id}:
    put:
      summary: Fazer Pedido
      description: Adiciona um item ao pedido do cliente.
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            format: int64
          description: ID do atendimento
        - in: query
          name: idItemCardapio
          required: true
          schema:
            type: integer
            format: int64
          description: ID do item do cardápio
      responses:
        '200':
          description: Pedido adicionado com sucesso.
  /restaurante/fechar-conta/{id}:
    put:
      summary: Fechar Conta
      description: Fecha a conta do cliente.
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            format: int64
          description: ID do atendimento
      responses:
        '200':
          description: Conta fechada com sucesso.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseComanda'
  /restaurante/requisicoes:
    get:
      summary: Listar Requisições
      description: Lista as requisições de atendimento.
      parameters:
        - in: query
          name: ativa
          required: false
          schema:
            type: boolean
          description: Filtra requisições ativas
      responses:
        '200':
          description: Lista de requisições
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Requisicao'
components:
  schemas:
    RequestAtenderClienteDTO:
      type: object
      properties:
        nomeCliente:
          type: string
        mesa:
          type: integer
          format: int32
    ResponseComanda:
      type: object
      properties:
        total:
          type: number
          format: double
        itens:
          type: array
          items:
            type: string
    Requisicao:
      type: object
      properties:
        id:
          type: integer
          format: int64
        descricao:
          type: string
        ativa:
          type: boolean