server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/lets-burn
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    org.springframework: DEBUG
    org.hibernate: DEBUG
