server:
  port:

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lets-burn-restaurante?useSSL=false&serverTimezone=UTC
    username: your_username
    password: your_password
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true # format SQL queries for better readability
logging:
  level:
    org.springframework: DEBUG
    org.hibernate: DEBUG
